spring:
  application:
    name: transacoes-api

  jackson:
    time-zone: America/Sao_Paulo

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true